### ISSUE TITLE
Univariate optimization is not robust

### ISSUE THREAD

**Issue by johnmyleswhite** [JuliaOpt/Optim.jl#106]
I'm not an expert on univariate optimization, but I believe that our current implementations are not as robust as they should be. Consider the following examples of trying to find a function's unique root by optimizing squared error:

```jl
using Optim

invlogit(z) = z < -3 ? 0.0 : z > 3 ? 1.0 : 1 / (1 + exp(-z))
obj(z) = (invlogit(z) - 0.5)^2

optimize(obj, -2, 2, method = :brent).minimum
optimize(obj, -2, 100, method = :brent).minimum

optimize(obj, -2, 2, method = :golden_section).minimum
optimize(obj, -2, 100, method = :golden_section).minimum
```

Note that changing the width of the search interval causes serious problems, even though the search interval continues the unique minimizer in all causes.

Contrast this with the behavior of `fzero` in the Roots package, which does not have similar problems with search intervals:

```jl
using Roots

invlogit(z) = z < -3 ? 0.0 : z > 3 ? 1.0 : 1 / (1 + exp(-z))
roots(z) = invlogit(z) - 0.5

fzero(roots, -2, 2)
fzero(roots, -2, 100)
```

**Comment by pkofod** [comment]
Golden section:
We calculate f(c1) and f(c2) as functions of f(a) and f(b). In our problem with the large interval, the problem is, that f(c1) = f(c2) because c1,c2 > 3. Normally we conclude that the optimum is in [a,c2] if f(c1) < f(c2) and conversely if f(c2) < f(c1). There is no check, as far as I can see, that f(c1) = f(c2) in our code. This would normally cause termination, since we would not be able to conclude if the minimum was in [a,c2] or [c1,b]. In addition, it should flag to the user, that we might have ended up in a flat region.

We could, I guess, make a "modified" golden section method the takes this into account, but comparing the final function value to f(a_start) and f(b_start). However, "golden section" really shouldn't be able to handle the problem at hand, since the golden sections between (-2,100) and (100,-2) are both > 3, and thus out of the "nice" region. To work, a and b would have to be chosen such that at least one of the golden sections are in [-3,3]. 

Compared to fzero, the problem is probably, that we are throwing the sign-information away by squaring.

**Comment by andreasnoack** [comment]
Neither R nor MATLAB is able to do better here which is probably no surprise for the reasons @pkofod gives. I think this is just at case where finding the root directly is easier than minimizing the squared problem because of the large flat region. Furthermore, I think `fzero` uses bisection which is hard to beat in terms of robustness.
