### ISSUE TITLE
levenberg-marquardt algorithm

### ISSUE THREAD

**Issue by prezaei85** [JuliaOpt/Optim.jl#108]
If J is sparse, levenberg-marquardt algorithm raises an error: http://stackoverflow.com/questions/28953961/a-ldiv-b-with-sparse-matrices. It seems like the solution is to put "-J'*fcur" on line 58 in parantheses: (-J'*fcur).

By the way, if I edit levenberg-marquardt.jl in my local files in the "Optim" package, will my package work OK in the future? Will it update and remove my edits or keep them? How does it work?

**Comment by mlubin** [comment]
I don't think the implementation was designed with sparse matrices in mind (and it's definitely not as efficient as it could be), but given that the fix is simple, I went ahead and applied it. Thanks for the report and detective work.
If you make changes locally, then the package will be marked as "dirty" and won't receive any updates. It would be best if you could submit and bug fixes you have as pull requests (http://docs.julialang.org/en/release-0.3/manual/packages/#making-changes-to-an-existing-package), this requires investing a bit of time into understanding how git and github work.
