### ISSUE TITLE
RFC: AdaDelta

### ISSUE THREAD

**Issue by oxinabox** [JuliaOpt/Optim.jl#119]
I've been hearing a lot about AdaGrad, and AdaDelta,
see [this discussion](https://groups.google.com/forum/#!topic/julia-opt/yQ1CsMPLDm4)

I have constructed and evaluated a rough implementation that should be direct compatable with Optim:
[See this Notebook](http://nbviewer.ipython.org/gist/oxinabox/f1cf9253b116e885839c).

However, it does not seem to work well,
so I wanted to get some feedback before I cleaned it up into a PR.

**Comment by mlubin** [comment]
I'm not an expert in these algorithms, but not using a line search for gradient descent seems pretty unusual.

**Comment by johnmyleswhite** [comment]
I don't think AdaGrad is an appropriate algorithm for submitting to this package. It's primarily useful when:

* You're fitting a model for which reaching a local optimum isn't important because objective function melioration is sufficient.
* You need to use O(p) memory to fit a model with p parameters over N observations, because you're working with a large data set that can't be fully stored in memory in a dense array.

In general, Optim is meant to only contain algorithms that have strong finite time guarantees when you attempt to optimize a deterministic function. AdaGrad isn't such an algorithm and would break many things in the Optim codebase, since we always assume that a function can be safely evaluated arbitrarily many times at a fixed point without changing the objective function's value -- an assumption that would be false when working on the stochastic optimization problems for which AdaGrad is appropriate.

All that said, if you're interested in learning more about SGD algorithms for your own edification, there are many very good papers published by folks like Leon Bottou. Contrasting those papers with a classic non-linear optimization textbook like Nocedal and Wright would teach you a lot about the ways in which AdaGrad is out of scope for Optim.jl.

There are also some existing codes in Julia that use AdaGrad to address specific problems whose strong convexity ensures that AdaGrad behaves reasonably well (see, e.g. StreamStats.jl). You may find them useful if you'd like to learn more about how to implement AdaGrad efficiently in Julia.
