### ISSUE TITLE
CG results f_minimum differs from f(minimum)

### ISSUE THREAD

**Issue by multidis** [JuliaOpt/Optim.jl#167]
Multivariate results [type](https://github.com/JuliaOpt/Optim.jl/blob/master/src/types.jl#L24) contains `f_minimum` field that differs from the value of objective function at the minimum point:

    rosenbrock(x::Array) = (1.0 - x[1])^2 + 100.0*(x[2] - x[1]^2)^2
    optres = Optim.fminbox(Optim.DifferentiableFunction(rosenbrock),
                       zeros(2), -10*ones(2), 10*ones(2),
                       optimizer = Optim.cg, iterations = 1_000)
    println(optres.f_minimum)
    println(Optim.DifferentiableFunction(rosenbrock).f(optres.minimum))

-4.5951198447245615e-8
5.597549090140484e-17

Noticed that first when receiving negative values for minimal sum-squares etc.

I am working with the `teh/constrained` branch by @timholy but Optim-master shows the same problem.

**Comment by pkofod** [comment]
On mobile,but it is because the negative number is actually your objectives function plus the barrierer function as far as I can see.

**Comment by multidis** [comment]
I see now, `fminbox` adds a barrier penalty **before** calling `CG`, thus the result type contains objective + barrier.

Perhaps making a note of this e.g. in the `README` [here](https://github.com/JuliaOpt/Optim.jl#box-minimization) would help future users as it is less than obvious. Leaving the issue open for someone to consider doing that.

**Comment by pkofod** [comment]
That is exactly why. `resultsnew` is the optimization result of `dfbox`, and since `results` stems from that, `f_minimum` ends up being the minimum of the function + barrier. Either we want to add a last construction of a `MultivariateOptimizationResults` calculating `f_minimum`, or we should add it to the README. Personally, I would expect to see the `f_minimum` of the actual function I was minimizing, but there might be a reason for returning the other result.

In your case, you're getting a kind of funky result, because you know your function is strictly positive, but in general the difference should be minimal (otherwise the method wouldn't be working :)).

I'd be willing to fix it either way, I just don't know if it is deliberate or not as it is.

**Comment by multidis** [comment]
> In your case, you're getting a kind of funky result, because you know your function is strictly positive, but in general the difference should be minimal (otherwise the method wouldn't be working :)).

True, the negative value is small. However, in my case it matters what is the exact minimum of the objective function within a given box. Turns out the values I was using are wrong since I was naively taking `f_minimum` field of the (yet) undocumented results-type. Thanks for helping catch that.
