### ISSUE TITLE
ERROR: UndefVarError: LBFGS not defined

### ISSUE THREAD

**Issue by Kindpire** [JuliaOpt/Optim.jl#176]
When I ran the sample of the latest Optim 0.4.4 in Julia 0.4.3, I got
 ERROR: UndefVarError: LBFGS not defined
with the code:
optimize(f, [0.0, 0.0], LBFGS())
but without the method name, everything is all good.
Any insights?
Thanks!

**Comment by pkofod** [comment]
That sounds odd. Can you post the output of `Pkg.status("Optim")`? Does it work with `NelderMead()`?

**Comment by pkofod** [comment]
@Kindpire, version 0.4.4 is not the version the README you see on `github.com/JuliaOpt/Optim.jl/` is for. To use the latest version you have to `Pkg.checkout("Optim")` in your terminal. We should probably state this in the readme at the top, since this is not the first confusion after the new API was merged.

**Comment by Kindpire** [comment]
Oh, you are right, it works now.
Thanks!

**Comment by pkofod** [comment]
You're welcome. Always nice to see that the package is being used!
