### ISSUE TITLE
Nelder-Mead gradient converged?

### ISSUE THREAD

**Issue by multidis** [JuliaOpt/Optim.jl#239]
In the past, Nelder-Mead was returning `f_converged` around [here](https://github.com/JuliaOpt/Optim.jl/blob/master/src/nelder_mead.jl#L225). Currently, Nelder-Mead returns gradient-converged in [this test](https://github.com/JuliaOpt/Optim.jl/blob/master/test/nelder_mead.jl#L28) for instance.

I could have missed something within the recent API change commits, but it seems confusing that a gradient-free method exits with the gradient convergence flag. Was the change intentional or is it a bug?
@pkofod 

Also related to the [show](https://github.com/JuliaOpt/Optim.jl/blob/master/src/types.jl#L149) method.

**Comment by pkofod** [comment]
It is actually intended, but what is not intended is that it is not in the README! I will have to fix and tag a patch. 

Why are we doing it like this? Well, it is basically because there are 3 different convergence criterions: f_tol, g_tol, and x_tol. I figured it would be easier to simply use the g_tol for the main convergence measure in Nelder-Mead. The problem is, that if we use f_tol, it will get the same default as other solvers, and that is a bit too small I think (1e-32). 

The convergence measure in NelderMead is not the gradient, but it does sort of measure how much the function varies around the centroid. That's why I didn't think it would be too bad to use `g_tol` as long as it was documented - it unfortunately isn't on the current stable release.

**Comment by pkofod** [comment]
Also, if you're using NelderMead a lot, you may want to be aware of some of the changes in #220 . The initial step size is going to change, the constructor, and the values of the four different parameters will as well. It shouldn't really break anything unless you're setting the parameters manually.

**Comment by multidis** [comment]
I guess one can think of the convergence check resembling the gradient, although it is less than a straightforward connection. The `f_tol` default is of course too small for Nelder-Mead, I'd imagine anyone using the method would change that.

A Readme note would indeed help remember this aspect (I had a number of tests failing that were expecting f_converged to be true). Thank you for clarifying.

**Comment by pkofod** [comment]
> I guess one can think of the convergence check resembling the gradient, although it is less than a straightforward connection. The f_tol default is of course too small for Nelder-Mead, I'd imagine anyone using the method would change that.
> 
> A Readme note would indeed help remember this aspect (I had a number of tests failing that were expecting f_converged to be true). Thank you for clarifying.

Yes, this is quite clearly a mistake on my part, it should have been documented properly. At least it should be in the master docs.

Also, thanks for reporting this. It's great to get feedback to see where things might go wrong/be unclear in the wild!
