### ISSUE TITLE
Linesearch fails when derivative is zero

### ISSUE THREAD

**Issue by anriseth** [JuliaOpt/Optim.jl#261]
I have a problem using (L)BFGS when the initial guess is the exact minimiser. The linesearch algorithm does not seem to like this:
```julia
f(x) = x[1]^2
optimize(f, [0.0], LBFGS(), OptimizationOptions(autodiff=true, show_trace=true, extended_trace=true))
```
Prints:
```julia
Iter     Function value   Gradient norm 
     0     0.000000e+00     0.000000e+00
 * Current step size: 1.0
 * g(x): [0.0]
 * x: [0.0]
ERROR: Search direction is not a direction of descent; this error may indicate that user-provided derivatives are inaccurate. (dphia = 0.000000; dphib = 0.000000)
 in error at ./error.jl:21
 [inlined code] from printf.jl:145
 in secant2! at /home/riseth/.julia/v0.4/Optim/src/linesearch/hz_linesearch.jl:412
 in hz_linesearch! at /home/riseth/.julia/v0.4/Optim/src/linesearch/hz_linesearch.jl:321
 in hz_linesearch! at /home/riseth/.julia/v0.4/Optim/src/linesearch/hz_linesearch.jl:176 (repeats 10 times)
 in optimize at /home/riseth/.julia/v0.4/Optim/src/l_bfgs.jl:186
 in optimize at /home/riseth/.julia/v0.4/Optim/src/optimize.jl:150
```

**Comment by anriseth** [comment]
One way to fix this would be to assess_convergence at the beginning of `optimize`, before the algorithms look for search directions etc. 
Is there a reason for why this is not done?

**Comment by pkofod** [comment]
Well, I guess no one has gotten around to it yet. It's actually a known problem, but I can't seem to find the issue. Some people have had this issue because they're solving a sequence of optimization problems, where the old solution for sequence iteration K is very close to the new solution for sequence iteration K+1. We should fix this.

**Comment by pkofod** [comment]
We could check for convergence at the beginning, but more generally I would like line search errors to soft exit instead of a hard error. The current setup makes debugging difficult, as you end up without an optimization output if a single line search step fails.

**Comment by anriseth** [comment]
Okay, so there are two separate issues here:
- Assess convergence at the start of the algorithms (but after applying a nonlinear preconditioner, if Optim ever gets that far). Maybe something #254 would deal with?
- Handle linesearch errors in a better way.

**Comment by pkofod** [comment]
I will keep it in mind for #254!

**Comment by anriseth** [comment]
For now, #262 would fix this issue.

**Comment by johnmyleswhite** [comment]
> We could check for convergence at the beginning, but more generally I would like line search errors to soft exit instead of a hard error

Originally I made everything throw hard errors because I wanted to avoid the situation with GLM fitting in R where you get nonsense results back, but only a minor warning is printed along the way. I now think that was too extreme, but I do still worry that if you just return results, many people won't check the converged flag. Maybe we need a mixed return object that contains the results in one field and error information in another? Not quite sure how, but ideally it would be cheap to get the results when there were no errors, but costly to get them when there were.

**Comment by anriseth** [comment]
It would be good to get the results from the steps in an algorithm that fails as well, but I agree that it needs to be very clear to the user if the result they get is rubbish or not.

I find it useful to give the user the opportunity to allow a given number of linesearch failures before the optimization algorithm fails (default to zero). 
Then, if the linesearch fails, the optimization algorithm would take a predefined step length and try again from this position.

**Comment by pkofod** [comment]
I agree about the dangers, but I think it should be possible to debug the optimization attempt. We could return NaN as optimum and array of NaNs as minimizer. Do you propose we make separate api to fetch info from a failed attempt?

**Comment by anriseth** [comment]
NaNs should make the user aware that something is wrong :+1: 
I think a separate api sounds a bit overkill, but being able to inspect a stored extended trace from the algorithm (and linesearch, preconditioner etc.) after a run is useful - both on success and failure.

**Comment by johnmyleswhite** [comment]
FWIW, here's my preferred approach, but it will take some time and work:

* In the future, we should never throw errors that we can avoid. `optimize` should always produce a results object.
* But the results object should store information about all errors that were encountered along the way.
* If no errors were encountered, the current API should produce exactly the results we give at the moment. We shouldn't make this case any harder.
* But if errors were encountered, the API should require you to take some extra steps to get access to the internals. The easiest way to do this, but the most verbose, would be to add `unsafe_FOO` methods for everything in the API. An alternative approach would be to use a `Nullable`, but add new methods for that `Nullable` that make it act like the existing object.

I personally think the `unsafe_FOO` approach is the best, since it also helps users diagnose code that is doing something potentially unsafe.

**Comment by pkofod** [comment]
Re-opened for the discussion - or should we take it elsewhere?

**Comment by pkofod** [comment]
As mentioned in the #262 PR, this means that the algorithm will assess a local maximum as "converged". I don't think we can do much about this besides documenting this fact. If that is not optimal, we could perturb the initial_x just a little, and hopefully enough that the line search won't complain.

**Comment by anriseth** [comment]
I'm not sure perturbing is a good idea. The initial guess may have been chosen deliberately. You might also end up moving an initial guess closer to a local maximum.

**Comment by pkofod** [comment]
Me neither, just mentioned it as *an* option. Ive simply documented it.
