### ISSUE TITLE
Minimum vs Minimiser

### ISSUE THREAD

**Issue by cortner** [JuliaOpt/Optim.jl#286]
This is in some ways a trivial issue, but I stumbled over it several times already and then have to go look which fields of `result` have which meaning: the *minimum* is the value of the energy at the *minimiser* (or, minimizer if you must) - see e.g. Nocedal/Wright, Sec. 2.1. 

I suggest to rename `result.minimum` to become `result.minimizer` or `result.solution` or `result.final_x`. Anything will do.

**Comment by pkofod** [comment]
Well, if you look at the function based API, we already made this switch. The reason why it hasn't been changed yet, is because we cannot deprecate field names. Therefore, I gave a warning in one of the tags where I said "Please use the function API, as we will fix this naming inconsistency in the fields at some point." I think it would be fair to say that people have had a fair warning by now, so I'm all for making the transition.

ref: #76 #165

**Comment by anriseth** [comment]
I agree that res.minimum is inappropriate and ambiguous.

I prefer solution or minimizer.

**Comment by pkofod** [comment]
It's going to be minimizer as in the results grabbing API, no worries. We just havn't made the (breaking) change yet.

**Comment by cortner** [comment]
ok - thank you; I'll use function calls then. as long as I know this will at some point be addressed, do you just want to close this then?

**Comment by pkofod** [comment]
No, let's keep it open until it is actually fixed.

**Comment by hrobotron** [comment]
Ah, thanksfully I've found this notice -- I almost went crazy thinking about being insane, and wondered, how did my (slightly!) older code managed to work so well, when I discovered I am using .minimum and not .minimizer. Now I know there was the API change. Huh, just hope that there are not so many other people in this trap.

(BTW, nothing against the change and the new wording. Maybe there could be some warning msg when upgrading to incompatible APIs... -- this very often happen due to a chain of other dependencies.)

**Comment by pkofod** [comment]
I'm sorry for the inconvenience, but you cannot deprecate field names. This is exactly why you are supposed to use `Optim.minimizer(result)` and not `result.minimizer`. If we ever want to change the functions name, we can now deprecate it.

It's been written that way in the documentation for a long time now (since before last summer), and I've announced it several times on the mailing list. I've also tried open issues in packages using the field access. Unfortunately, I havn't been able to think of more ways to communicate this. Maybe it should have been written in bold at the top of the README.

Again, sorry for the inconvenience. I've tried this myself, and I know how annoying it can be.

**Comment by hrobotron** [comment]
> This is exactly why you are supposed to use Optim.minimizer(result) and not result.minimizer.

Many thanks for guiding me to the correct way.

**Comment by pkofod** [comment]
> Many thanks for guiding me to the correct way.

:+1:

I know how these things go. I don't check the documentation of every package I use when they tag a new version either, so... Just glad it is sorted out! Please do submit an issue if you have any further problems.
